export const ipssiTecho = [
   'POO et MVC avec PHP 7 et 8, Symfony 6',
   'JavaScript – ECMA 6',
   'Node.js, server développement, API REST',
   'ReactJS',
   'Python et POO Python',
   'UML & MVC architectures',
   'Flutter développement mobile, Templating, interactions et animations Flutter',
   'Design d’interface UI/UX design avec Figma',
   'Git et Github',
   'Heroku, Gitlab et CI/CD',
   'Docker et Kubernetes',
   'Mongoose – MongoDB & CRUD systèmes',
   'Gestion de projet AGILE et SCRUM',
   "Soutenance de mon mémoire : Comment les services web et les nouvelles technologies améliorent l'interopérabilité dans les projets d'ingénierie ?",
   'Soutenance du projet annuel',
]

export const ocTechno = [
   '- Transformer une maquette en site web HTML/CSS',
   '- Créer et dynamiser un site avec HTML/CSS/SASS',
   '- Optimiser un site web existant (SEO)',
   '- Construire un site e-commerce en JavaScript',
   '- Créer une API sécurisée avec NodeJs/Express/MongoDB',
   "- Création d'un mini-réseau social d'entreprise avec ReactJS.",
]

export const esgiTechno = [
   'Cryptographie',
   'Signatures numériques',
   'Fonctions de hachage',
   'Panorama de la Blockchain : métiers, usage, Smart Contracts, dApps et DAOs',
   'Structures de données',
   'Protocole Bitcoin, protocole Ethereum',
   'Protocoles de consensus',
   'Blockchain Day et Hackathon Blockchain',
   'Algorithmique avancée : listes, tris et arbres',
   'Langage C avancé',
   'Python',
   'Versioning & Fondamentaux de Git',
   'Bases de données SQL/NoSQL',
   'MongoDB',
   'API avec Node.js',
   'Conteneurisation Docker',
   'Développement Front avec React',
   'Linux administration avancée',
   'Protocoles et services internet',
   'Architectures avancées des réseaux P2P',
   'Cœur de métier : banque et assurance',
   'Crypto-économie',
   'Réglementation et devises numériques',
   'Planification de projets SI : cadrage, lots, MS Project',
   'Anglais : vocabulaire business, préparation au TOEIC',
]
